### ISSUE TITLE
Feat : 데일리 퀴즈 정답 시 포인트 부여

### ISSUE THREAD

**Issue by eunjeeing** [Dream-wings/Dreamwing-Server#5]
## 🍀 Description
데일리 퀴즈 정답 시 포인트를 부여하는 기능을 구현합니다. 

## ✅ Todo
- [x] USER 테이블 point 업데이트 후 POINT_HISTORY 데이터 추가 프로시저 생성

## ETC
기타사항

**Comment by JAESEONGIM** [comment]
good code
